### ISSUE TITLE
Feature: Open daily notes from big calendar

### ISSUE THREAD

**Issue by HEmile** [Quorafind/Obsidian-Big-Calendar#2]
It would be nice if you could for example right click on a day to open the corresponding daily note for that date. That will also make it easier to change tasks

**Comment by wenlzhang** [comment]
It would also be very useful if one can open/create Weekly/Monthly and other types of notes supported by the Periodic Notes plugin: https://github.com/liamcain/obsidian-periodic-notes.

**Comment by Quorafind** [comment]
@HEmile In next release, you could click and then jump to the event, in the near future, will allow you to change the event in the calendar rather than jump to the dailynote

**Comment by Quorafind** [comment]
Available in [0.1.11](https://github.com/Quorafind/Obsidian-Big-Calendar/releases/tag/0.1.11)
