### ISSUE TITLE
当天的日程安排未出现在日历中

### ISSUE THREAD

**Issue by lillian-who** [Quorafind/Obsidian-Big-Calendar#3]
任何视图都没有出现。

![P%L}}VJR)DH F}(P8@05G3T](https://user-images.githubusercontent.com/20553685/146347749-d115dc87-3fd9-49bc-afbd-6b124591c28c.png)

**Comment by lillian-who** [comment]
我发现，需要重启库才可以显示新加的日程

**Comment by Quorafind** [comment]
在最新的 Release 中修复。
